version: "3"

services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  db:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ram1999
