# Generated by Django 4.0.4 on 2022-05-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_allviews_table_alter_todayview_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('private_key', models.CharField(max_length=255)),
                ('created_at', models.CharField(max_length=64)),
            ],
        ),
    ]
