# Generated by Django 4.0.4 on 2022-05-25 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_premiumusers_alter_users_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='premiumusers',
            table='premium_users',
        ),
    ]
