# Generated by Django 4.0.4 on 2022-05-25 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_premiumusers_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='premiumusers',
            table='premium_user',
        ),
    ]
