# Generated by Django 4.0.4 on 2022-05-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_premiumusers_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('chat_id', models.IntegerField()),
            ],
            options={
                'db_table': 'private_key',
            },
        ),
    ]
