# Generated by Django 4.0.4 on 2022-05-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_privatekey'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
                ('usage_du', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user_usage',
            },
        ),
    ]
