# Generated by Django 4.0.4 on 2022-05-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_userusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
                ('width', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=32)),
                ('file_id', models.CharField(max_length=255)),
                ('shortcode', models.CharField(max_length=32)),
                ('caption', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'file_information',
            },
        ),
    ]
