# Generated by Django 4.0.4 on 2022-05-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_userfileinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfileinfo',
            name='name',
            field=models.CharField(default='YouTubeDl', max_length=255),
        ),
    ]
