# Generated by Django 4.0.4 on 2022-05-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_userfileinfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfileinfo',
            name='chat_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userfileinfo',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
