# Generated by Django 4.0.4 on 2022-05-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_payinfo_usemyaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUsageU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
                ('usage_do', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user_works',
            },
        ),
    ]
