# Generated by Django 4.0.4 on 2022-06-17 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_userusageu_userworks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usemyaccount',
            options={'managed': False},
        ),
    ]
